version = 0.1

[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "carterascolectivas"
github_repo = "sam-app"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::086486166147:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1PLWXQOY5IJHK"
cloudformation_execution_role = "arn:aws:iam::086486166147:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1O7KS8ZNWXTIS"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-p87tg9448vkm"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::086486166147:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1H357I238J5U4"
cloudformation_execution_role = "arn:aws:iam::086486166147:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-L7UWO8LL1OEI"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-5whqwtk4mord"
image_repository = ""
region = "us-east-1"
